
interface Question {
  id: number;
  type: string;
  text: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

// These common questions will be used as fallbacks
const commonQuestionsByType: Record<string, Question[]> = {
  behavioral: [
    { id: 1, type: 'behavioral', text: 'Tell me about yourself and your background.', difficulty: 'beginner' },
    { id: 2, type: 'behavioral', text: 'Can you describe a time when you had to deal with a difficult teammate?', difficulty: 'intermediate' },
    { id: 3, type: 'behavioral', text: 'Tell me about a time you failed and what you learned from it.', difficulty: 'intermediate' },
    { id: 4, type: 'behavioral', text: 'How do you handle stress and pressure in your work?', difficulty: 'intermediate' },
    { id: 5, type: 'behavioral', text: 'Describe a situation where you had to make an unpopular decision.', difficulty: 'advanced' },
    { id: 6, type: 'behavioral', text: 'Tell me about a time you received difficult feedback and how you responded to it.', difficulty: 'intermediate' },
    { id: 7, type: 'behavioral', text: 'Describe a situation where you had to adapt to a significant change.', difficulty: 'intermediate' },
    { id: 8, type: 'behavioral', text: 'Give an example of when you showed initiative at work.', difficulty: 'beginner' },
    { id: 9, type: 'behavioral', text: 'Tell me about a time you had to manage multiple priorities simultaneously.', difficulty: 'intermediate' },
    { id: 10, type: 'behavioral', text: 'Describe a situation where you had to work effectively under pressure.', difficulty: 'intermediate' },
    { id: 11, type: 'behavioral', text: 'Share an example of when you had to persuade others to adopt your perspective.', difficulty: 'advanced' },
    { id: 12, type: 'behavioral', text: 'Tell me about a time you went above and beyond for a customer or client.', difficulty: 'intermediate' },
    { id: 13, type: 'behavioral', text: 'Describe a difficult ethical decision you had to make at work.', difficulty: 'advanced' },
    { id: 14, type: 'behavioral', text: 'Tell me about a time you had to deliver bad news to someone.', difficulty: 'intermediate' },
    { id: 15, type: 'behavioral', text: 'Give an example of how you\'ve contributed to a positive team culture.', difficulty: 'intermediate' },
    { id: 16, type: 'behavioral', text: 'Describe a situation where you had to resolve a conflict between team members.', difficulty: 'advanced' },
    { id: 17, type: 'behavioral', text: 'Tell me about a time you had to learn something quickly to solve a problem.', difficulty: 'intermediate' },
    { id: 18, type: 'behavioral', text: 'Share an example of a goal you set for yourself and how you achieved it.', difficulty: 'beginner' },
    { id: 19, type: 'behavioral', text: 'Tell me about a time you had to work with someone whose personality was very different from yours.', difficulty: 'intermediate' },
    { id: 20, type: 'behavioral', text: 'Describe a situation where you had to motivate a disengaged team member.', difficulty: 'advanced' },
  ],
  technical: [
    { id: 1, type: 'technical', text: 'Can you explain your approach to debugging a complex technical issue?', difficulty: 'beginner' },
    { id: 2, type: 'technical', text: 'How do you stay updated with the latest technologies in your field?', difficulty: 'beginner' },
    { id: 3, type: 'technical', text: 'Describe a challenging technical project you worked on and how you approached it.', difficulty: 'intermediate' },
    { id: 4, type: 'technical', text: 'How would you design a scalable web application architecture?', difficulty: 'advanced' },
    { id: 5, type: 'technical', text: 'Explain how you would implement a complex feature with significant technical constraints.', difficulty: 'advanced' },
    { id: 6, type: 'technical', text: 'How do you approach testing in your development process?', difficulty: 'intermediate' },
    { id: 7, type: 'technical', text: 'Describe your experience with continuous integration and deployment.', difficulty: 'intermediate' },
    { id: 8, type: 'technical', text: 'How would you optimize a slow-performing application or database?', difficulty: 'advanced' },
    { id: 9, type: 'technical', text: 'Explain your approach to system security and preventing common vulnerabilities.', difficulty: 'advanced' },
    { id: 10, type: 'technical', text: 'How do you handle technical debt in a codebase?', difficulty: 'intermediate' },
    { id: 11, type: 'technical', text: 'Describe your experience with microservices architecture.', difficulty: 'advanced' },
    { id: 12, type: 'technical', text: 'How would you design a RESTful API for a new service?', difficulty: 'intermediate' },
    { id: 13, type: 'technical', text: 'Explain your approach to data modeling for a complex application.', difficulty: 'advanced' },
    { id: 14, type: 'technical', text: 'How do you ensure code quality in a team environment?', difficulty: 'intermediate' },
    { id: 15, type: 'technical', text: 'Describe your experience with cloud services and infrastructure.', difficulty: 'intermediate' },
    { id: 16, type: 'technical', text: 'How would you implement authentication and authorization in a web application?', difficulty: 'intermediate' },
    { id: 17, type: 'technical', text: 'Explain your approach to handling real-time data and events.', difficulty: 'advanced' },
    { id: 18, type: 'technical', text: 'How do you approach troubleshooting in a production environment?', difficulty: 'intermediate' },
    { id: 19, type: 'technical', text: 'Describe your experience with version control and branching strategies.', difficulty: 'beginner' },
    { id: 20, type: 'technical', text: 'How would you design a system to handle high traffic loads?', difficulty: 'advanced' },
  ],
  leadership: [
    { id: 1, type: 'leadership', text: 'Describe your leadership style and how it has evolved over time.', difficulty: 'beginner' },
    { id: 2, type: 'leadership', text: 'Tell me about a time you had to lead a team through a difficult situation.', difficulty: 'intermediate' },
    { id: 3, type: 'leadership', text: 'How do you handle conflicts within your team?', difficulty: 'intermediate' },
    { id: 4, type: 'leadership', text: 'Describe how you have mentored or developed team members in the past.', difficulty: 'intermediate' },
    { id: 5, type: 'leadership', text: 'How do you make difficult decisions that might be unpopular with your team?', difficulty: 'advanced' },
    { id: 6, type: 'leadership', text: 'How do you delegate responsibilities to your team members?', difficulty: 'intermediate' },
    { id: 7, type: 'leadership', text: 'Describe a time when you had to lead a team with diverse skill levels and backgrounds.', difficulty: 'advanced' },
    { id: 8, type: 'leadership', text: 'How do you handle performance issues with team members?', difficulty: 'advanced' },
    { id: 9, type: 'leadership', text: 'Describe your approach to setting goals and measuring success for your team.', difficulty: 'intermediate' },
    { id: 10, type: 'leadership', text: 'How do you foster innovation and creative thinking in your team?', difficulty: 'advanced' },
    { id: 11, type: 'leadership', text: 'Tell me about a time you had to lead a team through a major organizational change.', difficulty: 'advanced' },
    { id: 12, type: 'leadership', text: 'How do you build trust with your team members?', difficulty: 'intermediate' },
    { id: 13, type: 'leadership', text: 'Describe your approach to giving constructive feedback.', difficulty: 'intermediate' },
    { id: 14, type: 'leadership', text: 'How do you motivate team members who are facing challenges or burnout?', difficulty: 'advanced' },
    { id: 15, type: 'leadership', text: 'Tell me about a time you had to make a difficult strategic decision.', difficulty: 'advanced' },
    { id: 16, type: 'leadership', text: 'How do you handle situations where team members disagree with your direction?', difficulty: 'intermediate' },
    { id: 17, type: 'leadership', text: 'Describe how you balance tactical execution with strategic planning.', difficulty: 'advanced' },
    { id: 18, type: 'leadership', text: 'How do you approach succession planning for key roles on your team?', difficulty: 'advanced' },
    { id: 19, type: 'leadership', text: 'Tell me about a time you had to lead a cross-functional team or initiative.', difficulty: 'intermediate' },
    { id: 20, type: 'leadership', text: 'How do you ensure your team stays aligned with broader organizational goals?', difficulty: 'intermediate' },
  ],
  industry: [
    { id: 1, type: 'industry', text: 'What trends do you see shaping our industry in the next few years?', difficulty: 'beginner' },
    { id: 2, type: 'industry', text: 'How do you stay updated on industry developments and best practices?', difficulty: 'beginner' },
    { id: 3, type: 'industry', text: 'What is your perspective on recent major industry developments?', difficulty: 'intermediate' },
    { id: 4, type: 'industry', text: 'How would you apply your experience to the specific challenges we face in this industry?', difficulty: 'intermediate' },
    { id: 5, type: 'industry', text: 'How do you adapt to rapid changes in industry standards and regulations?', difficulty: 'advanced' },
    { id: 6, type: 'industry', text: 'What do you think are the biggest challenges facing our industry today?', difficulty: 'intermediate' },
    { id: 7, type: 'industry', text: 'How have you seen technology transform this industry, and what further changes do you anticipate?', difficulty: 'intermediate' },
    { id: 8, type: 'industry', text: 'How does this industry compare to others in terms of innovation and adaptation?', difficulty: 'intermediate' },
    { id: 9, type: 'industry', text: 'What competitive strategies have you seen work well in this industry?', difficulty: 'advanced' },
    { id: 10, type: 'industry', text: 'How do you think consumer behaviors are changing in relation to our industry?', difficulty: 'intermediate' },
    { id: 11, type: 'industry', text: 'What regulatory challenges do you anticipate affecting this industry in the coming years?', difficulty: 'advanced' },
    { id: 12, type: 'industry', text: 'How do global economic trends impact our specific industry?', difficulty: 'advanced' },
    { id: 13, type: 'industry', text: 'What best practices from other industries do you think could be applied to ours?', difficulty: 'intermediate' },
    { id: 14, type: 'industry', text: 'How do you evaluate the success of different business models in our industry?', difficulty: 'advanced' },
    { id: 15, type: 'industry', text: 'What role do you think sustainability plays in the future of our industry?', difficulty: 'intermediate' },
    { id: 16, type: 'industry', text: 'How has the pandemic changed our industry, and which changes do you think will remain permanent?', difficulty: 'intermediate' },
    { id: 17, type: 'industry', text: 'What emerging markets or segments do you see as opportunities for our industry?', difficulty: 'advanced' },
    { id: 18, type: 'industry', text: 'How do you think artificial intelligence and automation will impact our industry?', difficulty: 'intermediate' },
    { id: 19, type: 'industry', text: 'What key performance indicators do you think are most important in our industry?', difficulty: 'intermediate' },
    { id: 20, type: 'industry', text: 'How do you think customer expectations in our industry have evolved over the past five years?', difficulty: 'intermediate' },
  ],
  case: [
    { id: 1, type: 'case', text: 'Our company is facing declining market share. How would you approach this problem?', difficulty: 'intermediate' },
    { id: 2, type: 'case', text: 'We need to launch a new product in 6 months. Walk me through your approach.', difficulty: 'intermediate' },
    { id: 3, type: 'case', text: 'How would you evaluate the potential of a new market opportunity?', difficulty: 'intermediate' },
    { id: 4, type: 'case', text: 'Our costs have increased by 20% while revenue remains flat. What strategies would you implement?', difficulty: 'advanced' },
    { id: 5, type: 'case', text: 'We are considering an acquisition of a competitor. How would you evaluate this decision?', difficulty: 'advanced' },
    { id: 6, type: 'case', text: 'Our customer retention rate has dropped 15% over the past year. How would you investigate and address this?', difficulty: 'advanced' },
    { id: 7, type: 'case', text: 'We need to reduce operational costs by 30%. How would you approach this challenge?', difficulty: 'advanced' },
    { id: 8, type: 'case', text: 'A new competitor has entered our market with a disruptive pricing model. How should we respond?', difficulty: 'advanced' },
    { id: 9, type: 'case', text: 'Our company is considering expanding into international markets. What factors would you analyze?', difficulty: 'intermediate' },
    { id: 10, type: 'case', text: 'Our marketing campaigns have shown diminishing returns. How would you revitalize our approach?', difficulty: 'intermediate' },
    { id: 11, type: 'case', text: 'We need to improve our supply chain efficiency. What would your strategy include?', difficulty: 'intermediate' },
    { id: 12, type: 'case', text: 'Our engineering team is experiencing high turnover. How would you diagnose and address this issue?', difficulty: 'advanced' },
    { id: 13, type: 'case', text: 'We want to shift from a traditional sales model to a subscription model. How would you manage this transition?', difficulty: 'advanced' },
    { id: 14, type: 'case', text: 'A key supplier has informed us they can no longer meet our volume requirements. What would you do?', difficulty: 'intermediate' },
    { id: 15, type: 'case', text: 'Our company needs to decide between two major strategic initiatives with limited resources. How would you approach this decision?', difficulty: 'advanced' },
    { id: 16, type: 'case', text: 'How would you develop a pricing strategy for a new service with no direct market comparisons?', difficulty: 'advanced' },
    { id: 17, type: 'case', text: 'Our customer satisfaction scores are lagging behind competitors. How would you improve them?', difficulty: 'intermediate' },
    { id: 18, type: 'case', text: 'We need to integrate two very different company cultures after an acquisition. What would your plan include?', difficulty: 'advanced' },
    { id: 19, type: 'case', text: 'Our product development cycles are too long. How would you streamline them?', difficulty: 'intermediate' },
    { id: 20, type: 'case', text: 'How would you evaluate the ROI of implementing a new enterprise software system?', difficulty: 'intermediate' },
  ],
  performance: [
    { id: 1, type: 'performance', text: 'Describe your biggest professional achievement and what made it successful.', difficulty: 'beginner' },
    { id: 2, type: 'performance', text: 'How do you measure success in your current role?', difficulty: 'beginner' },
    { id: 3, type: 'performance', text: 'Tell me about a project where you exceeded expectations.', difficulty: 'intermediate' },
    { id: 4, type: 'performance', text: 'How do you prioritize competing tasks and objectives?', difficulty: 'intermediate' },
    { id: 5, type: 'performance', text: 'Describe a situation where you had to significantly improve a process or outcome.', difficulty: 'advanced' },
    { id: 6, type: 'performance', text: 'How do you track and evaluate your own performance?', difficulty: 'intermediate' },
    { id: 7, type: 'performance', text: 'Tell me about a time you had to meet an extremely tight deadline.', difficulty: 'intermediate' },
    { id: 8, type: 'performance', text: 'How have you improved efficiency or productivity in your previous roles?', difficulty: 'intermediate' },
    { id: 9, type: 'performance', text: 'Describe a situation where you identified and solved a problem before it was apparent to others.', difficulty: 'advanced' },
    { id: 10, type: 'performance', text: 'How do you handle situations where you need to work with limited resources?', difficulty: 'intermediate' },
    { id: 11, type: 'performance', text: 'Tell me about a time you set and achieved an ambitious goal.', difficulty: 'intermediate' },
    { id: 12, type: 'performance', text: 'How do you balance quality and speed in your work?', difficulty: 'intermediate' },
    { id: 13, type: 'performance', text: 'Describe how you\'ve used data or metrics to improve your performance.', difficulty: 'advanced' },
    { id: 14, type: 'performance', text: 'Tell me about a time when you had to overcome significant obstacles to achieve a goal.', difficulty: 'advanced' },
    { id: 15, type: 'performance', text: 'How do you handle situations where you miss a target or deadline?', difficulty: 'intermediate' },
    { id: 16, type: 'performance', text: 'Describe a situation where you had to make a tough decision regarding resource allocation.', difficulty: 'advanced' },
    { id: 17, type: 'performance', text: 'How do you maintain high performance during periods of significant stress or change?', difficulty: 'advanced' },
    { id: 18, type: 'performance', text: 'Tell me about a time you identified a way to save costs or resources.', difficulty: 'intermediate' },
    { id: 19, type: 'performance', text: 'How do you continuously improve your skills and knowledge to enhance performance?', difficulty: 'beginner' },
    { id: 20, type: 'performance', text: 'Describe a situation where you had to pivot your approach to achieve the desired outcome.', difficulty: 'intermediate' },
  ],
};

// Role-specific questions
const roleSpecificQuestions: Record<string, Record<string, Question[]>> = {
  'Software Engineer': {
    behavioral: [
      { id: 1, type: 'behavioral', text: 'Tell me about a time you had to learn a new programming language or framework quickly.', difficulty: 'intermediate' },
      { id: 2, type: 'behavioral', text: 'Describe a situation where you had to debug a critical production issue under pressure.', difficulty: 'advanced' },
      { id: 3, type: 'behavioral', text: 'Give an example of when you had to refactor poorly written code.', difficulty: 'intermediate' },
      { id: 4, type: 'behavioral', text: 'Tell me about a time you disagreed with a team member about a technical decision.', difficulty: 'intermediate' },
      { id: 5, type: 'behavioral', text: 'Describe a project where you had to work with legacy code.', difficulty: 'intermediate' },
      { id: 6, type: 'behavioral', text: 'Tell me about a time you had to make a trade-off between quality and meeting a deadline.', difficulty: 'intermediate' },
      { id: 7, type: 'behavioral', text: 'Describe a situation where you suggested an improvement to a development process.', difficulty: 'intermediate' },
      { id: 8, type: 'behavioral', text: 'How have you handled code reviews and feedback on your work?', difficulty: 'beginner' },
      { id: 9, type: 'behavioral', text: 'Tell me about a time you had to communicate a complex technical concept to non-technical stakeholders.', difficulty: 'intermediate' },
      { id: 10, type: 'behavioral', text: 'Describe how you stay updated with technology trends and continuously learn.', difficulty: 'beginner' },
      { id: 11, type: 'behavioral', text: 'Tell me about a time when you improved the performance of an application.', difficulty: 'advanced' },
      { id: 12, type: 'behavioral', text: 'How do you approach testing your code?', difficulty: 'intermediate' },
      { id: 13, type: 'behavioral', text: 'Describe a situation where you had to write documentation for your code.', difficulty: 'beginner' },
      { id: 14, type: 'behavioral', text: 'Tell me about a time you contributed to an open-source project.', difficulty: 'intermediate' },
      { id: 15, type: 'behavioral', text: 'How have you mentored junior developers in the past?', difficulty: 'intermediate' },
      { id: 16, type: 'behavioral', text: 'Describe a challenging bug you fixed and how you approached it.', difficulty: 'intermediate' },
      { id: 17, type: 'behavioral', text: 'Tell me about a time you had to optimize database queries.', difficulty: 'advanced' },
      { id: 18, type: 'behavioral', text: 'How do you handle technical debt in your projects?', difficulty: 'intermediate' },
      { id: 19, type: 'behavioral', text: 'Describe a situation where you had to implement a feature with ambiguous requirements.', difficulty: 'intermediate' },
      { id: 20, type: 'behavioral', text: 'Tell me about a time you had to balance multiple projects simultaneously.', difficulty: 'intermediate' },
    ],
    technical: [
      { id: 1, type: 'technical', text: 'Explain the concept of object-oriented programming and its principles.', difficulty: 'beginner' },
      { id: 2, type: 'technical', text: 'How would you design a scalable RESTful API?', difficulty: 'intermediate' },
      { id: 3, type: 'technical', text: 'Explain the difference between synchronous and asynchronous programming.', difficulty: 'beginner' },
      { id: 4, type: 'technical', text: 'How would you optimize the performance of a slow web application?', difficulty: 'advanced' },
      { id: 5, type: 'technical', text: 'Describe your experience with version control systems like Git.', difficulty: 'beginner' },
      { id: 6, type: 'technical', text: 'What testing strategies and tools do you use?', difficulty: 'intermediate' },
      { id: 7, type: 'technical', text: 'How would you handle database migrations in a production environment?', difficulty: 'advanced' },
      { id: 8, type: 'technical', text: 'Explain the concept of microservices architecture and its advantages.', difficulty: 'intermediate' },
      { id: 9, type: 'technical', text: 'How do you ensure security in your applications?', difficulty: 'advanced' },
      { id: 10, type: 'technical', text: 'Describe your experience with CI/CD pipelines.', difficulty: 'intermediate' },
      { id: 11, type: 'technical', text: 'What approaches do you use for optimizing database queries?', difficulty: 'advanced' },
      { id: 12, type: 'technical', text: 'How would you implement caching in a web application?', difficulty: 'intermediate' },
      { id: 13, type: 'technical', text: 'Explain how you would handle error handling and logging in a production application.', difficulty: 'intermediate' },
      { id: 14, type: 'technical', text: 'How would you design a system to handle real-time data?', difficulty: 'advanced' },
      { id: 15, type: 'technical', text: 'What is your approach to code reviews?', difficulty: 'beginner' },
      { id: 16, type: 'technical', text: 'How would you implement authentication and authorization in a web application?', difficulty: 'intermediate' },
      { id: 17, type: 'technical', text: 'Explain how you would design a database schema for a complex application.', difficulty: 'advanced' },
      { id: 18, type: 'technical', text: 'How would you handle concurrency issues in a multi-threaded application?', difficulty: 'advanced' },
      { id: 19, type: 'technical', text: 'What design patterns do you commonly use and why?', difficulty: 'intermediate' },
      { id: 20, type: 'technical', text: 'How do you approach refactoring legacy code?', difficulty: 'intermediate' },
    ],
  },
  'Product Manager': {
    behavioral: [
      { id: 1, type: 'behavioral', text: 'Tell me about a time when you had to prioritize features for a product roadmap.', difficulty: 'intermediate' },
      { id: 2, type: 'behavioral', text: 'Describe a situation where you had to make a decision with incomplete information.', difficulty: 'intermediate' },
      { id: 3, type: 'behavioral', text: 'Tell me about a time you had to say no to a feature request from a key stakeholder.', difficulty: 'advanced' },
      { id: 4, type: 'behavioral', text: 'How have you gathered and incorporated user feedback into your products?', difficulty: 'beginner' },
      { id: 5, type: 'behavioral', text: 'Describe a time when you had to launch a product under a tight deadline.', difficulty: 'intermediate' },
      { id: 6, type: 'behavioral', text: 'Tell me about a product you managed from conception to launch.', difficulty: 'intermediate' },
      { id: 7, type: 'behavioral', text: 'How have you worked with engineers to ensure technical feasibility of your product ideas?', difficulty: 'intermediate' },
      { id: 8, type: 'behavioral', text: 'Describe a situation where you had to make trade-offs between user experience and business requirements.', difficulty: 'advanced' },
      { id: 9, type: 'behavioral', text: 'Tell me about a time when a product launch didn\'t go as planned. What did you learn?', difficulty: 'advanced' },
      { id: 10, type: 'behavioral', text: 'How do you communicate product vision and strategy to different stakeholders?', difficulty: 'intermediate' },
      { id: 11, type: 'behavioral', text: 'Describe a time when you had to pivot your product strategy based on market changes.', difficulty: 'advanced' },
      { id: 12, type: 'behavioral', text: 'Tell me about a time you identified a new market opportunity for your product.', difficulty: 'intermediate' },
      { id: 13, type: 'behavioral', text: 'How have you balanced competing priorities from different departments?', difficulty: 'intermediate' },
      { id: 14, type: 'behavioral', text: 'Describe a situation where you had to lead cross-functional teams to achieve a product goal.', difficulty: 'intermediate' },
      { id: 15, type: 'behavioral', text: 'Tell me about a time you had to make a data-driven product decision.', difficulty: 'intermediate' },
      { id: 16, type: 'behavioral', text: 'How do you measure the success of your products?', difficulty: 'beginner' },
      { id: 17, type: 'behavioral', text: 'Describe a time when you had to convince skeptical stakeholders about a product direction.', difficulty: 'advanced' },
      { id: 18, type: 'behavioral', text: 'Tell me about a time you collaborated with design and engineering teams effectively.', difficulty: 'intermediate' },
      { id: 19, type: 'behavioral', text: 'How have you incorporated competitive analysis into your product strategy?', difficulty: 'intermediate' },
      { id: 20, type: 'behavioral', text: 'Describe a situation where you had to make a difficult decision about sunsetting a product feature.', difficulty: 'advanced' },
    ],
    technical: [
      { id: 1, type: 'technical', text: 'What product metrics do you typically track and why?', difficulty: 'beginner' },
      { id: 2, type: 'technical', text: 'How do you approach A/B testing and experimentation?', difficulty: 'intermediate' },
      { id: 3, type: 'technical', text: 'Explain your process for writing effective product requirements documents.', difficulty: 'beginner' },
      { id: 4, type: 'technical', text: 'How do you prioritize your product backlog?', difficulty: 'intermediate' },
      { id: 5, type: 'technical', text: 'Describe your experience with agile development methodologies.', difficulty: 'beginner' },
      { id: 6, type: 'technical', text: 'How would you determine the pricing strategy for a new product?', difficulty: 'advanced' },
      { id: 7, type: 'technical', text: 'What tools and processes do you use for product analytics?', difficulty: 'intermediate' },
      { id: 8, type: 'technical', text: 'How do you conduct market research to validate product ideas?', difficulty: 'intermediate' },
      { id: 9, type: 'technical', text: 'Explain how you create and use user personas in your product development process.', difficulty: 'beginner' },
      { id: 10, type: 'technical', text: 'How would you structure a product roadmap for the next 12 months?', difficulty: 'intermediate' },
      { id: 11, type: 'technical', text: 'Describe your process for competitive analysis.', difficulty: 'beginner' },
      { id: 12, type: 'technical', text: 'How do you measure and improve user retention?', difficulty: 'advanced' },
      { id: 13, type: 'technical', text: 'What methodologies do you use for user research?', difficulty: 'intermediate' },
      { id: 14, type: 'technical', text: 'How do you balance short-term fixes with long-term product vision?', difficulty: 'advanced' },
      { id: 15, type: 'technical', text: 'Explain your approach to product localization for international markets.', difficulty: 'intermediate' },
      { id: 16, type: 'technical', text: 'How do you create alignment between product strategy and company objectives?', difficulty: 'advanced' },
      { id: 17, type: 'technical', text: 'What frameworks do you use for making product decisions?', difficulty: 'intermediate' },
      { id: 18, type: 'technical', text: 'How would you approach monetization for a freemium product?', difficulty: 'advanced' },
      { id: 19, type: 'technical', text: 'Explain how you use customer journey mapping in your product development process.', difficulty: 'intermediate' },
      { id: 20, type: 'technical', text: 'How do you validate that you\'re building the right product for your target market?', difficulty: 'intermediate' },
    ],
  },
  // Add more roles as needed...
};

export const getQuestionsByType = (type: string, role: string): Question[] => {
  // First try to get role-specific questions
  const lowerRole = role.toLowerCase();
  
  // Check if we have specific questions for this role
  const matchedRole = Object.keys(roleSpecificQuestions).find(
    r => lowerRole.includes(r.toLowerCase()) || r.toLowerCase().includes(lowerRole)
  );
  
  if (matchedRole && roleSpecificQuestions[matchedRole][type]) {
    return roleSpecificQuestions[matchedRole][type];
  }
  
  // Fall back to common questions if no role-specific questions are found
  return commonQuestionsByType[type] || [];
};
